title: Codeing
author: Vedran Hrnčić
email: vedran.hrncic@gmail.com
description: >-
  Codeing company pages
baseurl: /codeing
url: https://vr4b4c.github.io

theme: no-style-please

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y.%m.%d"
  show_description: false

plugins:
  - jekyll-feed
